server:
  port: 8085

turbine:
  appConfig: consul,auth-service,exam-service,user-service,gateway-service
  aggregator:
    clusterConfig: CONSUL,AUTH-SERVICE,EXAM-SERVICE,USER-SERVICE,GATEWAY-SERVICE

spring:
  security:
    user:
      name: admin
      password: 11
  boot:
    admin:
      context-path: /admin
      client:
        enabled: false
        auto-registration: false
      instance:
        service-base-url: http://localhost:${server.port}
  # sleuth 配置
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 采样比例为: 0.1(即10%),设置的值介于0.0到1.0之间，1.0则表示全部采集。
  # zipkin 配置
  zipkin:
    base-url: http://localhost:9411  # 指定了Zipkin服务器的地址